# Generated by Django 4.2 on 2023-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_name", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe_name",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="recipe_name"),
        ),
    ]
