# Generated by Django 4.2 on 2023-04-14 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Directions",
            new_name="Direction",
        ),
    ]
