# Generated by Django 4.2 on 2023-05-11 03:01

from django.db import migrations, models
import django.db.models.deletion
import recipe_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_name",
                    models.CharField(default="none listed", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe_app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "pic",
                    models.ImageField(
                        default="no_picture.jpg", upload_to="recipe_name"
                    ),
                ),
                ("directions", models.CharField(max_length=2000)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[recipe_app.models.validate_minutes]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe_ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(default=0)),
                (
                    "unit_of_measurement",
                    models.CharField(default="none listed", max_length=200),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        default="none listed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe_app.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        default="none listed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe_app.recipe_app",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe_app",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipe_app.Recipe_ingredient", to="recipe_app.ingredient"
            ),
        ),
    ]
