# Generated by Django 4.2 on 2023-05-03 19:31

from django.db import migrations, models
import recipe_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe_app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "pic",
                    models.ImageField(
                        default="no_picture.jpg", upload_to="recipe_name"
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("unit_of_measurement", models.CharField(max_length=200)),
                ("directions", models.CharField(max_length=2000)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[recipe_app.models.validate_minutes]
                    ),
                ),
            ],
        ),
    ]
