# Generated by Django 4.2 on 2023-06-27 18:22

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeDetailView",
            fields=[
                (
                    "recipe_app_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="recipe_app.recipe_app",
                    ),
                ),
            ],
            bases=(
                django.contrib.auth.mixins.LoginRequiredMixin,
                "recipe_app.recipe_app",
            ),
        ),
        migrations.CreateModel(
            name="RecipeListView",
            fields=[
                (
                    "recipe_app_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="recipe_app.recipe_app",
                    ),
                ),
            ],
            bases=(
                django.contrib.auth.mixins.LoginRequiredMixin,
                "recipe_app.recipe_app",
            ),
        ),
    ]
