# Generated by Django 4.2 on 2023-07-22 00:41

from django.db import migrations, models
import recipe_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_app", "0003_remove_recipelistview_recipe_app_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_app",
            name="minutes",
            field=models.PositiveIntegerField(
                validators=[recipe_app.models.validate_minutes]
            ),
        ),
    ]
